name: 01 - Daily Export
# Purpose: Runs every day at 10 PM EST to export trading data from PropReports
# What it does:
#   1. Exports today's trades
#   2. Reprocesses last 3 days (for late-reported trades)
#   3. Triggers stats update and GitHub Pages deployment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Daily at 10 PM EST

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Export PropReports Data
      uses: jefrnc/propreports-auto-exporter@v1
      with:
        propreports-domain: ${{ secrets.PROPREPORTS_DOMAIN }}
        propreports-user: ${{ secrets.PROPREPORTS_USER }}
        propreports-pass: ${{ secrets.PROPREPORTS_PASS }}
        reprocess-days: '3'
        obfuscate-account: 'true'
    
    - name: Trigger Stats Update
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: update-stats
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'