name: 03 - Reprocess Last Year
# Purpose: Manual workflow to reprocess 1 full year of historical data
# Use when:
#   - You need complete annual data
#   - Year-end analysis
#   - Major data recovery
# What it does:
#   1. Exports 365 days of trading data
#   2. Triggers stats update and GitHub Pages deployment

on:
  workflow_dispatch:

jobs:
  reprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Export PropReports Data (Last Year)
      uses: jefrnc/propreports-auto-exporter@v1
      with:
        propreports-domain: ${{ secrets.PROPREPORTS_DOMAIN }}
        propreports-user: ${{ secrets.PROPREPORTS_USER }}
        propreports-pass: ${{ secrets.PROPREPORTS_PASS }}
        reprocess-days: '365'     # 1 year
        obfuscate-account: 'true'
    
    - name: Trigger Stats Update
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: update-stats
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'