name: Export Trading Data

on:
  workflow_dispatch: # Solo manual para pruebas
  schedule:
    - cron: '0 3 * * *' # Diario a las 10 PM EST

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Export PropReports Data
      uses: jefrnc/propreports-auto-exporter@v1
      with:
        propreports-domain: ${{ secrets.PROPREPORTS_DOMAIN }}
        propreports-user: ${{ secrets.PROPREPORTS_USER }}
        propreports-pass: ${{ secrets.PROPREPORTS_PASS }}