name: Generate Weekly Summaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-summaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboard repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout exporter repository
        uses: actions/checkout@v4
        with:
          repository: jefrnc/propreports-auto-exporter
          path: exporter
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml requests numpy

      - name: Generate weekly summaries
        run: |
          # Copy scripts from exporter
          cp exporter/src/weekly_summary.py .
          
          # Generate weekly summaries for all weeks since April
          cat > generate_all_weekly.py << 'EOF'
          import subprocess
          import os
          from datetime import datetime, timedelta
          
          # Set environment variable
          os.environ['EXPORT_OUTPUT_DIR'] = 'exports'
          
          # Start from April 1, 2025
          start_date = datetime(2025, 4, 1)
          end_date = datetime.now()
          
          current_date = start_date
          weeks_generated = []
          
          while current_date <= end_date:
              year = current_date.year
              week = current_date.isocalendar()[1]
              
              week_key = f"{year}-W{week:02d}"
              if week_key not in weeks_generated:
                  print(f"Generating summary for week {week_key}")
                  try:
                      subprocess.run(['python', 'weekly_summary.py', str(year), str(week)], check=True)
                      weeks_generated.append(week_key)
                  except subprocess.CalledProcessError as e:
                      print(f"Failed to generate summary for {week_key}: {e}")
                  except Exception as e:
                      print(f"Error generating summary for {week_key}: {e}")
              
              current_date += timedelta(days=7)
          EOF
          
          python generate_all_weekly.py

      - name: Commit weekly summaries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -d "exports/weekly/" ]; then
            git add exports/weekly/
          fi
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Generate weekly summaries from April to present"
            git push
          fi