name: Generate Monthly Summaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-summaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboard repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout exporter repository
        uses: actions/checkout@v4
        with:
          repository: jefrnc/propreports-auto-exporter
          path: exporter
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml requests numpy

      - name: Generate monthly summaries
        run: |
          # Copy scripts from exporter
          cp exporter/src/monthly_summary.py .
          
          # Generate monthly summaries for missing months
          cat > generate_missing_summaries.py << 'EOF'
          import subprocess
          import os
          
          # Set environment variable
          os.environ['EXPORT_OUTPUT_DIR'] = 'exports'
          
          # Months to generate
          months = [
              ('2025', '02'),
              ('2025', '03'),
              ('2025', '04'),
              ('2025', '05'),
              ('2025', '06')
          ]
          
          for year, month in months:
              print(f"Generating summary for {year}-{month}")
              try:
                  subprocess.run(['python', 'monthly_summary.py', year, month], check=True)
              except subprocess.CalledProcessError as e:
                  print(f"Failed to generate summary for {year}-{month}: {e}")
              except Exception as e:
                  print(f"Error generating summary for {year}-{month}: {e}")
          EOF
          
          python generate_missing_summaries.py

      - name: Commit monthly summaries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -d "exports/monthly/" ]; then
            git add exports/monthly/
          fi
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Generate monthly summaries for Feb-June 2025"
            git push
          fi