name: Reprocess Last Year

on:
  workflow_dispatch:

jobs:
  reprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Export PropReports Data (Last Year)
      uses: jefrnc/propreports-auto-exporter@v1
      with:
        propreports-domain: ${{ secrets.PROPREPORTS_DOMAIN }}
        propreports-user: ${{ secrets.PROPREPORTS_USER }}
        propreports-pass: ${{ secrets.PROPREPORTS_PASS }}
        reprocess-days: '365'     # 1 year
        obfuscate-account: 'true'