name: Update Trading Statistics

on:
  # Run after export workflow completes
  workflow_run:
    workflows: ["Export Trading Data"]
    types:
      - completed
  
  # Also allow manual trigger
  workflow_dispatch:
  
  # Run daily at 11 PM EST (after exports)
  schedule:
    - cron: '0 4 * * *'  # 4 AM UTC = 11 PM EST

jobs:
  update-stats:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml numpy
    
    - name: Download scripts
      run: |
        wget -q https://raw.githubusercontent.com/jefrnc/propreports-auto-exporter/main/src/generate_stats.py
        wget -q https://raw.githubusercontent.com/jefrnc/propreports-auto-exporter/main/src/generate_calendar.py
        wget -q https://raw.githubusercontent.com/jefrnc/propreports-auto-exporter/main/src/generate_dashboard_data.py
    
    - name: Update statistics
      run: |
        echo "📊 Updating trading statistics..."
        python generate_stats.py
        
        echo "📅 Generating calendar..."
        python generate_calendar.py
        
        echo "📈 Generating dashboard data..."
        python generate_dashboard_data.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Stats Update Bot"
        
        # Add all changes
        git add -A
        
        # Check if there are changes
        if git diff --quiet --cached; then
          echo "No changes to commit"
        else
          git commit -m "📊 Update trading statistics [skip ci]"
          git push
          echo "✅ Statistics updated successfully"
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2